spring:
  application:
    name: card-service

  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

    #url: jdbc:h2:mem:order_category_db;DB_CLOSE_ON_EXIT=FALSE
    #driver-class-name: org.h2.Driver
    #username: sa
    #password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
      #database-platform: org.hibernate.dialect.H2Dialect

      #h2:
      # console:
      #  enabled: true
    # path: /h2-console


  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

server:
  port: 8086