spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:product_category_db
    #;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create # Ou "create-drop" se desejar recriar o banco a cada inicializa��o
    database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false


  #spring:
  #  application:
  #    name: product-service
  #  config:
  #    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  # spring:
  #   config:
  #     import: optional:configserver:http://localhost:9999

server:
  port: 8083